/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 model.glb -o TimeMachine.tsx -t 
Author: InvisibleSpanish (https://sketchfab.com/InvisibleSpanish)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dragon-ball-time-machine-5d1ba82a7bdc4398aaa7e316ba1bce87
Title: Dragon Ball Time Machine
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Sphere_Material002_0: THREE.Mesh
    Sphere001_Base_0: THREE.Mesh
    Sphere002_Propulsores_0: THREE.Mesh
    Sphere002_Escudo_interior_0: THREE.Mesh
    Sphere003_Propulsores_0: THREE.Mesh
    Sphere004_Base_0: THREE.Mesh
    Cube004_Cabina_0: THREE.Mesh
    Cube003_Cabina_0: THREE.Mesh
    Sphere005_Cabina_0: THREE.Mesh
    Cylinder003_Mandos_0: THREE.Mesh
    Cylinder003_Mandos_Detalles_0: THREE.Mesh
    Plane_Detalles_Cabina_0: THREE.Mesh
    Cylinder006_Detalles_Cabina_0: THREE.Mesh
    Cube005_Detalles_Cabina_0: THREE.Mesh
    Cube006_Cabina_0: THREE.Mesh
    Sphere007_Mandos_0: THREE.Mesh
    Sphere007_Mandos_Detalles_0: THREE.Mesh
    Plane001_Detalles_Cabina_0: THREE.Mesh
    Plane002_Pantalla_0: THREE.Mesh
    Cylinder004_Detalles_Cabina_0: THREE.Mesh
    Plane003_Detalles_Cabina_0: THREE.Mesh
    Plane004_Detalles_Cabina_0: THREE.Mesh
    Plane005_Pantalla_0: THREE.Mesh
    Plane006_Detalles_Cabina_0: THREE.Mesh
    Cube008_Detalles_Cabina_0: THREE.Mesh
    Plane007_Pantalla_3_0: THREE.Mesh
    Plane010_Pantalla_2_0: THREE.Mesh
    Plane011_Detalles_Cabina_0: THREE.Mesh
    Plane009_Detalles_Cabina_0: THREE.Mesh
    Plane012_Cabina_0: THREE.Mesh
    Plane013_Cabina_0: THREE.Mesh
    Plane014_Cabina_0: THREE.Mesh
    Cube010_Pantalla_3_0: THREE.Mesh
    Cube011_Boton_1_0: THREE.Mesh
    Cylinder007_Mandos_Detalles_0: THREE.Mesh
    Plane016_Detalles_Cabina_0: THREE.Mesh
    Plane015_Pantalla_0: THREE.Mesh
    Cube012_Detalles_Cabina_0: THREE.Mesh
    Cylinder011_Detalles_Cabina_0: THREE.Mesh
    Cylinder012_Detalles_Cabina_0: THREE.Mesh
    Plane017_Detalles_Cabina_0: THREE.Mesh
    Cylinder013_Cabina_0: THREE.Mesh
    Plane018_Detalles_Cabina_0: THREE.Mesh
    Cylinder014_Cabina_0: THREE.Mesh
    Cylinder015_Cabina_0: THREE.Mesh
    Cylinder016_Cabina_0: THREE.Mesh
    Plane019_Detalles_Cabina_0: THREE.Mesh
    Plane019_Pantalla_3_0: THREE.Mesh
    Cylinder017_Detalles_Cabina_0: THREE.Mesh
    Cylinder018_Detalles_Cabina_0: THREE.Mesh
    Plane020_Detalles_Cabina_0: THREE.Mesh
    Plane021_Detalles_Cabina_0: THREE.Mesh
    Plane022_Detalles_Cabina_0: THREE.Mesh
    Plane023_Detalles_Cabina_0: THREE.Mesh
    Plane024_Detalles_Cabina_0: THREE.Mesh
    Cube015_Cabina_0: THREE.Mesh
    Plane026_Detalles_Cabina_0: THREE.Mesh
    Cube026_Cabina_0: THREE.Mesh
    Vert_Cabina_0: THREE.Mesh
    Cylinder019_Detalles_Cabina_0: THREE.Mesh
    Cylinder020_Detalles_Cabina_0: THREE.Mesh
    Plane025_Cabina_0: THREE.Mesh
    Plane027_Engranaje_0: THREE.Mesh
    Plane028_Engranaje_0: THREE.Mesh
    Plane031_Silla_0: THREE.Mesh
    Plane032_Detalles_Cabina_0: THREE.Mesh
    Plane033_Detalles_Cabina_0: THREE.Mesh
    Plane034_Detalles_Cabina_0: THREE.Mesh
    Cube027_Silla_0: THREE.Mesh
    Cylinder_Engranaje_0: THREE.Mesh
    Cylinder001_Engranaje_0: THREE.Mesh
    Cube_Propulsores_0: THREE.Mesh
    Cube001_Propulsores_0: THREE.Mesh
    Cube002_Propulsores_0: THREE.Mesh
    Cube002_Propulsores_Abajo_0: THREE.Mesh
    Cube002_Base_0: THREE.Mesh
    Cylinder002__0: THREE.Mesh
  }
  materials: {
    ['Material.002']: THREE.MeshPhysicalMaterial
    Base: THREE.MeshStandardMaterial
    Propulsores: THREE.MeshStandardMaterial
    Escudo_interior: THREE.MeshStandardMaterial
    Cabina: THREE.MeshStandardMaterial
    Mandos: THREE.MeshStandardMaterial
    Mandos_Detalles: THREE.MeshStandardMaterial
    Detalles_Cabina: THREE.MeshStandardMaterial
    Pantalla: THREE.MeshStandardMaterial
    Pantalla_3: THREE.MeshStandardMaterial
    Pantalla_2: THREE.MeshStandardMaterial
    Boton_1: THREE.MeshStandardMaterial
    Engranaje: THREE.MeshStandardMaterial
    Silla: THREE.MeshStandardMaterial
    Propulsores_Abajo: THREE.MeshStandardMaterial
    ['Cylinder.002__0']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/model.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[2.997, 201.246, 0]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={100}>
          <mesh geometry={nodes.Sphere002_Propulsores_0.geometry} material={materials.Propulsores} />
          <mesh geometry={nodes.Sphere002_Escudo_interior_0.geometry} material={materials.Escudo_interior} />
        </group>
        <group position={[76.008, 330.726, -29.435]} rotation={[-1.138, 0, 0]} scale={2.736}>
          <mesh geometry={nodes.Cylinder003_Mandos_0.geometry} material={materials.Mandos} />
          <mesh geometry={nodes.Cylinder003_Mandos_Detalles_0.geometry} material={materials.Mandos_Detalles} />
        </group>
        <group position={[38.457, 330.589, -50.766]} rotation={[Math.PI / 2, 0, 0]} scale={[-3.514, 5.946, 3.514]}>
          <mesh geometry={nodes.Sphere007_Mandos_0.geometry} material={materials.Mandos} />
          <mesh geometry={nodes.Sphere007_Mandos_Detalles_0.geometry} material={materials.Mandos_Detalles} />
        </group>
        <group position={[-18.344, 340.281, -56.564]} rotation={[-0.136, 0, 0]} scale={[203.505, 100, 100]}>
          <mesh geometry={nodes.Plane019_Detalles_Cabina_0.geometry} material={materials.Detalles_Cabina} />
          <mesh geometry={nodes.Plane019_Pantalla_3_0.geometry} material={materials.Pantalla_3} />
        </group>
        <group position={[2.997, 201.246, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube002_Propulsores_0.geometry} material={materials.Propulsores} />
          <mesh geometry={nodes.Cube002_Propulsores_Abajo_0.geometry} material={materials.Propulsores_Abajo} />
          <mesh geometry={nodes.Cube002_Base_0.geometry} material={materials.Base} />
        </group>
        <mesh geometry={nodes.Sphere_Material002_0.geometry} material={materials['Material.002']} position={[4.052, 409.495, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Sphere001_Base_0.geometry} material={materials.Base} position={[2.997, 201.246, 0]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[98.219, 98.219, 98.868]} />
        <mesh geometry={nodes.Sphere003_Propulsores_0.geometry} material={materials.Propulsores} position={[4.052, 95.852, 0]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={60.254} />
        <mesh geometry={nodes.Sphere004_Base_0.geometry} material={materials.Base} position={[4.052, 93.771, 0]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={67.06} />
        <mesh geometry={nodes.Cube004_Cabina_0.geometry} material={materials.Cabina} position={[3, 321.446, 0.002]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[42.888, 42.888, 100]} />
        <mesh geometry={nodes.Cube003_Cabina_0.geometry} material={materials.Cabina} position={[3, 321.495, 0.002]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[42.888, 42.888, 100]} />
        <mesh geometry={nodes.Sphere005_Cabina_0.geometry} material={materials.Cabina} position={[3.059, 326.174, -21.769]} rotation={[-1.709, 0, -0.177]} scale={27.195} />
        <mesh geometry={nodes.Plane_Detalles_Cabina_0.geometry} material={materials.Detalles_Cabina} position={[76.008, 331.433, -11.954]} rotation={[Math.PI / 2, 0, 0]} scale={[-6.838, 16.034, 6.838]} />
        <mesh geometry={nodes.Cylinder006_Detalles_Cabina_0.geometry} material={materials.Detalles_Cabina} position={[2.621, 304.751, -52.507]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[5.107, 12.915, 14.911]} />
        <mesh geometry={nodes.Cube005_Detalles_Cabina_0.geometry} material={materials.Detalles_Cabina} position={[2.626, 304.751, -52.881]} rotation={[-Math.PI / 2, 0, -0.029]} scale={[3.049, 3.719, 3.719]} />
        <mesh geometry={nodes.Cube006_Cabina_0.geometry} material={materials.Cabina} position={[39.986, 331.979, -53.149]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane001_Detalles_Cabina_0.geometry} material={materials.Detalles_Cabina} position={[2.953, 338.289, -55.144]} scale={[10.447, 9.534, 12.946]} />
        <mesh geometry={nodes.Plane002_Pantalla_0.geometry} material={materials.Pantalla} position={[2.953, 338.289, -55.728]} rotation={[-0.177, 0, 0]} scale={11.563} />
        <mesh geometry={nodes.Cylinder004_Detalles_Cabina_0.geometry} material={materials.Detalles_Cabina} position={[2.953, 338.297, -54.84]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[5.107, 12.915, 14.911]} />
        <mesh geometry={nodes.Plane003_Detalles_Cabina_0.geometry} material={materials.Detalles_Cabina} position={[36.855, 344.453, -57.043]} rotation={[3.007, 0, 0]} scale={[-3.349, 3.349, 3.349]} />
        <mesh geometry={nodes.Plane004_Detalles_Cabina_0.geometry} material={materials.Detalles_Cabina} position={[24.907, 340.535, -54.672]} rotation={[-1.711, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane005_Pantalla_0.geometry} material={materials.Pantalla} position={[26.749, 349.967, -57.63]} rotation={[-1.703, 0, 0]} scale={185.235} />
        <mesh geometry={nodes.Plane006_Detalles_Cabina_0.geometry} material={materials.Detalles_Cabina} position={[26.942, 350.268, -57.368]} rotation={[-1.703, 0, 0]} scale={205.55} />
        <mesh geometry={nodes.Cube008_Detalles_Cabina_0.geometry} material={materials.Detalles_Cabina} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane007_Pantalla_3_0.geometry} material={materials.Pantalla_3} position={[16.776, 353.308, -57.836]} rotation={[3.005, 0, 0]} scale={[-2.499, 2.499, 2.499]} />
        <mesh geometry={nodes.Plane010_Pantalla_2_0.geometry} material={materials.Pantalla_2} position={[16.776, 360.254, -58.787]} rotation={[3.005, 0, 0]} scale={[-2.499, 2.499, 2.499]} />
        <mesh geometry={nodes.Plane011_Detalles_Cabina_0.geometry} material={materials.Detalles_Cabina} position={[26.942, 350.268, -57.368]} rotation={[-1.703, 0, 0]} scale={205.55} />
        <mesh geometry={nodes.Plane009_Detalles_Cabina_0.geometry} material={materials.Detalles_Cabina} position={[3.168, 357.121, -57.863]} rotation={[3.005, 0, 0]} scale={[-9.132, 6.571, 6.571]} />
        <mesh geometry={nodes.Plane012_Cabina_0.geometry} material={materials.Cabina} position={[3.168, 360.944, -58.387]} rotation={[3.005, 0, 0]} scale={[-8.2, 1.874, 6.571]} />
        <mesh geometry={nodes.Plane013_Cabina_0.geometry} material={materials.Cabina} position={[3.168, 357.131, -57.865]} rotation={[3.005, 0, 0]} scale={[-8.2, 1.874, 6.571]} />
        <mesh geometry={nodes.Plane014_Cabina_0.geometry} material={materials.Cabina} position={[3.168, 353.38, -57.351]} rotation={[3.005, 0, 0]} scale={[-8.2, 1.874, 6.571]} />
        <mesh geometry={nodes.Cube010_Pantalla_3_0.geometry} material={materials.Pantalla_3} position={[-1.906, 365.081, -60.045]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube011_Boton_1_0.geometry} material={materials.Boton_1} position={[-1.916, 367.695, -60.435]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cylinder007_Mandos_Detalles_0.geometry} material={materials.Mandos_Detalles} position={[-32.468, 360.538, -37.208]} rotation={[Math.PI / 2, 0, 0]} scale={[-1.889, 1.889, 1.889]} />
        <mesh geometry={nodes.Plane016_Detalles_Cabina_0.geometry} material={materials.Detalles_Cabina} position={[-10.767, 358.163, -58.207]} rotation={[3.005, 0, 0]} scale={[-3.149, 4.193, 3.595]} />
        <mesh geometry={nodes.Plane015_Pantalla_0.geometry} material={materials.Pantalla} position={[-10.767, 358.143, -58.352]} rotation={[-0.136, 0, 0]} scale={[3.21, 4.504, 3.21]} />
        <mesh geometry={nodes.Cube012_Detalles_Cabina_0.geometry} material={materials.Detalles_Cabina} position={[-21.731, 356.074, -58.742]} rotation={[-0.136, 0, 0]} scale={[3.256, 1.456, 0.581]} />
        <mesh geometry={nodes.Cylinder011_Detalles_Cabina_0.geometry} material={materials.Detalles_Cabina} position={[-21.582, 350.264, -57.692]} scale={[4.02, 4.02, 2.037]} />
        <mesh geometry={nodes.Cylinder012_Detalles_Cabina_0.geometry} material={materials.Detalles_Cabina} position={[-21.582, 350.264, -56.435]} scale={[3.09, 3.09, 1.565]} />
        <mesh geometry={nodes.Plane017_Detalles_Cabina_0.geometry} material={materials.Detalles_Cabina} position={[-14.018, 343.682, -57.03]} rotation={[-0.136, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cylinder013_Cabina_0.geometry} material={materials.Cabina} position={[-14.018, 343.771, -56.382]} rotation={[-0.136, 0, 0]} scale={102.861} />
        <mesh geometry={nodes.Plane018_Detalles_Cabina_0.geometry} material={materials.Detalles_Cabina} position={[-22.687, 343.682, -57.03]} rotation={[-0.136, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cylinder014_Cabina_0.geometry} material={materials.Cabina} position={[-20.016, 343.771, -56.382]} rotation={[-0.136, 0, 0]} scale={102.861} />
        <mesh geometry={nodes.Cylinder015_Cabina_0.geometry} material={materials.Cabina} position={[-25.38, 343.771, -56.382]} rotation={[-0.136, 0, 0]} scale={102.861} />
        <mesh geometry={nodes.Cylinder016_Cabina_0.geometry} material={materials.Cabina} position={[-22.658, 343.771, -56.382]} rotation={[-0.136, 0, 0]} scale={102.861} />
        <mesh geometry={nodes.Cylinder017_Detalles_Cabina_0.geometry} material={materials.Detalles_Cabina} position={[-31.801, 341.759, -56.481]} rotation={[3.005, 0, 0]} scale={[-2.039, 2.039, 0.276]} />
        <mesh geometry={nodes.Cylinder018_Detalles_Cabina_0.geometry} material={materials.Detalles_Cabina} position={[-31.801, 341.863, -55.724]} rotation={[3.005, 0, 0]} scale={[-1.77, 1.77, 1.194]} />
        <mesh geometry={nodes.Plane020_Detalles_Cabina_0.geometry} material={materials.Detalles_Cabina} position={[26.942, 350.268, -57.368]} rotation={[-1.703, 0, 0]} scale={205.55} />
        <mesh geometry={nodes.Plane021_Detalles_Cabina_0.geometry} material={materials.Detalles_Cabina} position={[70.23, 332.254, 14.652]} rotation={[-Math.PI / 2, -0.065, 0]} scale={[4.842, 15.683, 29.034]} />
        <mesh geometry={nodes.Plane022_Detalles_Cabina_0.geometry} material={materials.Detalles_Cabina} position={[80.032, 332.89, 10.051]} rotation={[-Math.PI / 2, -0.065, 0]} scale={[4.842, 11.052, 29.034]} />
        <mesh geometry={nodes.Plane023_Detalles_Cabina_0.geometry} material={materials.Detalles_Cabina} position={[80.032, 332.89, 29.543]} rotation={[-Math.PI / 2, -0.065, 0]} scale={[4.842, 8.176, 29.034]} />
        <mesh geometry={nodes.Plane024_Detalles_Cabina_0.geometry} material={materials.Detalles_Cabina} position={[70.23, 332.254, 37.63]} rotation={[-Math.PI / 2, -0.065, 0]} scale={[4.842, 6.968, 29.034]} />
        <mesh geometry={nodes.Cube015_Cabina_0.geometry} material={materials.Cabina} position={[80.007, 333.254, 38.646]} rotation={[-Math.PI / 2, 0, 0]} scale={[157.78, 233.898, 157.78]} />
        <mesh geometry={nodes.Plane026_Detalles_Cabina_0.geometry} material={materials.Detalles_Cabina} position={[3, 321.495, 0.002]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[25.251, 21.862, 21.862]} />
        <mesh geometry={nodes.Cube026_Cabina_0.geometry} material={materials.Cabina} position={[4.729, 333.029, 83.45]} rotation={[-1.598, 0, 0]} scale={[20.933, 17.134, 31.366]} />
        <mesh geometry={nodes.Vert_Cabina_0.geometry} material={materials.Cabina} position={[5.005, 353.069, 82.181]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cylinder019_Detalles_Cabina_0.geometry} material={materials.Detalles_Cabina} position={[5.005, 353.069, 82.181]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cylinder020_Detalles_Cabina_0.geometry} material={materials.Detalles_Cabina} position={[5.005, 380.97, 68.237]} scale={100} />
        <mesh geometry={nodes.Plane025_Cabina_0.geometry} material={materials.Cabina} position={[3, 321.495, 0.002]} rotation={[-Math.PI / 2, 0, 0]} scale={[103.681, 100, 100]} />
        <mesh geometry={nodes.Plane027_Engranaje_0.geometry} material={materials.Engranaje} position={[3, 321.495, 0.002]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane028_Engranaje_0.geometry} material={materials.Engranaje} position={[3, 292.021, 0.002]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane031_Silla_0.geometry} material={materials.Silla} position={[3, 321.495, 0.002]} rotation={[-Math.PI / 2, 0, 0]} scale={[6.793, 14.205, 9.201]} />
        <mesh geometry={nodes.Plane032_Detalles_Cabina_0.geometry} material={materials.Detalles_Cabina} position={[26.942, 350.268, -57.368]} rotation={[-1.703, 0, 0]} scale={205.55} />
        <mesh geometry={nodes.Plane033_Detalles_Cabina_0.geometry} material={materials.Detalles_Cabina} position={[26.942, 343.232, -56.431]} rotation={[-1.703, 0, 0]} scale={205.55} />
        <mesh geometry={nodes.Plane034_Detalles_Cabina_0.geometry} material={materials.Detalles_Cabina} position={[26.942, 343.232, -56.431]} rotation={[-1.703, 0, 0]} scale={205.55} />
        <mesh geometry={nodes.Cube027_Silla_0.geometry} material={materials.Silla} position={[4.341, 319.108, 26.381]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[27.702, 30.182, 27.702]} />
        <mesh geometry={nodes.Cylinder_Engranaje_0.geometry} material={materials.Engranaje} position={[2.997, 219.836, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cylinder001_Engranaje_0.geometry} material={materials.Engranaje} position={[2.997, 399.863, 0]} rotation={[Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube_Propulsores_0.geometry} material={materials.Propulsores} position={[2.443, 309.64, -0.349]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube001_Propulsores_0.geometry} material={materials.Propulsores} position={[2.997, 201.246, 0]} rotation={[-Math.PI / 2, 0, 0.615]} scale={100} />
        <mesh geometry={nodes.Cylinder002__0.geometry} material={materials['Cylinder.002__0']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/model.glb')
