/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/guardians-ship.glb -o src/ships/GuardiansShip.tsx -t
Author: razzie_mbessai (https://sketchfab.com/razzie_mbessai)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/guardians-of-the-galaxy-milano-mandela-spaceship-d41dfa4b160e403db99f1c3bbe06dcfc
Title: Guardians of the Galaxy Milano Mandela spaceship
*/

import { useGLTF } from '@react-three/drei'
import { SHIP_CONFIGS } from '../config/shipConfigs'
import type { Mesh } from 'three'
import type { GLTFResult } from '../types'

const config = SHIP_CONFIGS['guardians-ship']

export function GuardiansShip() {
  const { nodes, materials } = useGLTF('/models/guardians-ship.glb') as GLTFResult
  return (
    <group dispose={null}>
      <group
        scale={config.transform.scale}
        rotation={config.transform.rotation}
        position={config.transform.positionOffset}
      >
        <mesh geometry={(nodes.GotG_MilanoShape_airbrakeHinges_0 as Mesh).geometry} material={materials.airbrakeHinges} />
        <mesh geometry={(nodes.GotG_MilanoShape_airbrakesBack_0 as Mesh).geometry} material={materials.airbrakesBack} />
        <mesh geometry={(nodes.GotG_MilanoShape_airbrakesFront_0 as Mesh).geometry} material={materials.airbrakesFront} />
        <mesh geometry={(nodes.GotG_MilanoShape_mainBody_0 as Mesh).geometry} material={materials.mainBody} />
        <mesh geometry={(nodes.GotG_MilanoShape_underbellyVents_0 as Mesh).geometry} material={materials.underbellyVents} />
        <mesh geometry={(nodes.GotG_MilanoShape_frontBlasters_0 as Mesh).geometry} material={materials.frontBlasters} />
        <mesh geometry={(nodes.GotG_MilanoShape_shellBody_0 as Mesh).geometry} material={materials.shellBody} />
        <mesh geometry={(nodes.GotG_MilanoShape_cockpitGlass_0 as Mesh).geometry} material={materials.cockpitGlass} />
        <mesh geometry={(nodes.GotG_MilanoShape_cockpitFrame_0 as Mesh).geometry} material={materials.cockpitFrame} />
        <mesh geometry={(nodes.GotG_MilanoShape_wingButtons_0 as Mesh).geometry} material={materials.wingButtons} />
        <mesh geometry={(nodes.GotG_MilanoShape_rearEngines1_0 as Mesh).geometry} material={materials.rearEngines1} />
        <mesh geometry={(nodes.GotG_MilanoShape_rearEngines2_0 as Mesh).geometry} material={materials.rearEngines2} />
        <mesh geometry={(nodes.GotG_MilanoShape_rearEngines3_0 as Mesh).geometry} material={materials.rearEngines3} />
        <mesh geometry={(nodes.GotG_MilanoShape_wingExhausts_0 as Mesh).geometry} material={materials.wingExhausts} />
        <mesh geometry={(nodes.GotG_MilanoShape_fuselage_0 as Mesh).geometry} material={materials.fuselage} />
        <mesh geometry={(nodes.GotG_MilanoShape_frontLightsFrame_0 as Mesh).geometry} material={materials.frontLightsFrame} />
        <mesh geometry={(nodes.GotG_MilanoShape_frontLightsGlass_0 as Mesh).geometry} material={materials.frontLightsGlass} />
        <mesh geometry={(nodes.GotG_MilanoShape_frontLights_0 as Mesh).geometry} material={materials.frontLights} />
        <mesh geometry={(nodes.GotG_MilanoShape_wingIntakes_0 as Mesh).geometry} material={materials.wingIntakes} />
        <mesh geometry={(nodes.GotG_MilanoShape_chinHatches_0 as Mesh).geometry} material={materials.chinHatches} />
        <mesh geometry={(nodes.GotG_MilanoShape_chinIntakes_0 as Mesh).geometry} material={materials.chinIntakes} />
        <mesh geometry={(nodes.GotG_MilanoShape_lMiddleWinglet_0 as Mesh).geometry} material={materials.lMiddleWinglet} />
        <mesh geometry={(nodes.GotG_MilanoShape_rearWingletGears_0 as Mesh).geometry} material={materials.rearWingletGears} />
        <mesh geometry={(nodes.GotG_MilanoShape_rearWinglets_0 as Mesh).geometry} material={materials.rearWinglets} />
        <mesh geometry={(nodes.GotG_MilanoShape_topWingletGears_0 as Mesh).geometry} material={materials.topWingletGears} />
        <mesh geometry={(nodes.GotG_MilanoShape_topWinglets_0 as Mesh).geometry} material={materials.topWinglets} />
        <mesh geometry={(nodes.GotG_MilanoShape_wingHinges_0 as Mesh).geometry} material={materials.wingHinges} />
        <mesh geometry={(nodes.GotG_MilanoShape_hull_0 as Mesh).geometry} material={materials.hull} />
        <mesh geometry={(nodes.GotG_MilanoShape_rearBlasters_0 as Mesh).geometry} material={materials.rearBlasters} />
        <mesh geometry={(nodes.GotG_MilanoShape_rMiddleWinglet_0 as Mesh).geometry} material={materials.rMiddleWinglet} />
        <mesh geometry={(nodes.GotG_MilanoShape_rudders_0 as Mesh).geometry} material={materials.rudders} />
        <mesh geometry={(nodes.GotG_MilanoShape_sunroof_0 as Mesh).geometry} material={materials.sunroof} />
        <mesh geometry={(nodes.GotG_MilanoShape_tailfeathers_0 as Mesh).geometry} material={materials.tailfeathers} />
        <mesh geometry={(nodes.GotG_MilanoShape_aft_0 as Mesh).geometry} material={materials.material} />
        <mesh geometry={(nodes.GotG_MilanoShape_aftRocket_0 as Mesh).geometry} material={materials.aftRocket} />
        <mesh geometry={(nodes.GotG_MilanoShape_aftRocketExhaust_0 as Mesh).geometry} material={materials.aftRocketExhaust} />
        <mesh geometry={(nodes.GotG_MilanoShape_aftBooster_0 as Mesh).geometry} material={materials.aftBooster} />
        <mesh geometry={(nodes.GotG_MilanoShape_aftSideArmour_0 as Mesh).geometry} material={materials.aftSideArmour} />
        <mesh geometry={(nodes.GotG_MilanoShape_aftTopArmour_0 as Mesh).geometry} material={materials.aftTopArmour} />
        <mesh geometry={(nodes.GotG_MilanoShape_aftExhaust_0 as Mesh).geometry} material={materials.aftExhaust} />
        <mesh geometry={(nodes.GotG_MilanoShape_aftWindowFrame_0 as Mesh).geometry} material={materials.aftWindowFrame} />
        <mesh geometry={(nodes.GotG_MilanoShape_aftWindowGlass_0 as Mesh).geometry} material={materials.aftWindowGlass} />
        <mesh geometry={(nodes.GotG_MilanoShape_middleWinglets_0 as Mesh).geometry} material={materials.middleWinglets} />
        <mesh geometry={(nodes.GotG_MilanoShape_wingLightsFrame_0 as Mesh).geometry} material={materials.wingLightsFrame} />
        <mesh geometry={(nodes.GotG_MilanoShape_wingLights_0 as Mesh).geometry} material={materials.wingLights} />
        <mesh geometry={(nodes.GotG_MilanoShape_boosters_0 as Mesh).geometry} material={materials.boosters} />
        <mesh geometry={(nodes.GotG_MilanoShape_boostersTrim_0 as Mesh).geometry} material={materials.boostersTrim} />
        <mesh geometry={(nodes.GotG_MilanoShape_engineDiscs_0 as Mesh).geometry} material={materials.engineDiscs} />
        <mesh geometry={(nodes.GotG_MilanoShape_engineCores_0 as Mesh).geometry} material={materials.engineCores} />
        <mesh geometry={(nodes.GotG_MilanoShape_engineGrooves_0 as Mesh).geometry} material={materials.engineGrooves} />
        <mesh geometry={(nodes.GotG_MilanoShape_engineCircles_0 as Mesh).geometry} material={materials.engineCircles} />
        <mesh geometry={(nodes.GotG_MilanoShape_engineCovers_0 as Mesh).geometry} material={materials.engineCovers} />
        <mesh geometry={(nodes.GotG_MilanoShape_lBottomWinglet_0 as Mesh).geometry} material={materials.lBottomWinglet} />
        <mesh geometry={(nodes.GotG_MilanoShape_rBottomWinglet_0 as Mesh).geometry} material={materials.rBottomWinglet} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/guardians-ship.glb')
