/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 model.glb -o PlanetExpress.tsx -t 
Author: Raver (https://sketchfab.com/Raver)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/planet-express-spaceship-51eb6b7e17954c3fadd9a5c100f451b8
Title: Planet Express SpaceShip
*/

import { useGLTF } from '@react-three/drei'
import { SHIP_CONFIGS } from '../config/shipConfigs'
import { EnginePropulsion } from '../effects'
import type { Mesh } from 'three'
import type { GLTFResult } from '../types'

const config = SHIP_CONFIGS['planet-express']

export function PlanetExpress() {
  const { nodes, materials } = useGLTF('/models/planet-express.glb') as GLTFResult
  return (
    <group dispose={null}>
      <group
        scale={config.transform.scale}
        rotation={config.transform.rotation}
        position={config.transform.positionOffset}
      >
          <group position={[0.38, -54.128, -54.947]} rotation={[-1.566, 0, 0]} scale={0.027}>
            <group rotation={[Math.PI / 2, 0, 0]}>
              <group position={[96.433, 120.342, 288.369]} rotation={[-0.759, 0, 0]} scale={[27.105, 27.105, 48.298]}>
                <mesh geometry={(nodes.Cylinder012_Nave_0 as Mesh).geometry} material={materials.Nave} />
                <mesh geometry={(nodes.Cylinder012_Cristal_0 as Mesh).geometry} material={materials.Cristal} />
              </group>
              <group position={[284.189, 117.417, 285.488]} rotation={[-0.755, 0.052, 0.003]} scale={[27.105, 27.105, 48.298]}>
                <mesh geometry={(nodes.Cylinder013_Nave_0 as Mesh).geometry} material={materials.Nave} />
                <mesh geometry={(nodes.Cylinder013_Cristal_0 as Mesh).geometry} material={materials.Cristal} />
              </group>
              <group position={[447.864, 110.468, 271.061]} rotation={[-0.809, 0.131, 0.04]} scale={[27.105, 27.105, 48.298]}>
                <mesh geometry={(nodes.Cylinder014_Nave_0 as Mesh).geometry} material={materials.Nave} />
                <mesh geometry={(nodes.Cylinder014_Cristal_0 as Mesh).geometry} material={materials.Cristal} />
              </group>
              <group position={[551.152, 102.914, 253.105]} rotation={[-0.916, 0.24, 0.05]} scale={[27.105, 27.105, 48.298]}>
                <mesh geometry={(nodes.Cylinder015_Nave_0 as Mesh).geometry} material={materials.Nave} />
                <mesh geometry={(nodes.Cylinder015_Cristal_0 as Mesh).geometry} material={materials.Cristal} />
              </group>
              <group position={[680.587, 80.036, 101.393]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 97.842, 100]}>
                <mesh geometry={(nodes.Plane001_Nave_0 as Mesh).geometry} material={materials.Nave} />
                <mesh geometry={(nodes.Plane001_Cristal_0 as Mesh).geometry} material={materials.Cristal} />
              </group>
              <group position={[-734.493, -11.729, 94.69]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh geometry={(nodes.Cylinder021_Nave_0 as Mesh).geometry} material={materials.Nave} />
                <mesh geometry={(nodes.Cylinder021_LuzAzul_0 as Mesh).geometry} material={materials.LuzAzul} />
              </group>
              <group position={[216.976, 186.199, 100.209]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh geometry={(nodes.Cylinder005_Nave_0 as Mesh).geometry} material={materials.Nave} />
                <mesh geometry={(nodes.Cylinder005_Cristal_0 as Mesh).geometry} material={materials.Cristal} />
              </group>
              <mesh geometry={(nodes.Cylinder002_Nave_0 as Mesh).geometry} material={materials.Nave} position={[216.976, 186.199, 100.209]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <mesh geometry={(nodes.Cylinder003_Nave_0 as Mesh).geometry} material={materials.Nave} position={[-396.886, 146.566, 96.931]} rotation={[-Math.PI / 2, -0.199, 0]} scale={[200, 200, 200.345]} />
              <mesh geometry={(nodes.Cylinder001_Nave_0 as Mesh).geometry} material={materials.Nave} position={[81.465, -15.511, 100.393]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
              <mesh geometry={(nodes.Cylinder011_Nave_0 as Mesh).geometry} material={materials.Nave} position={[157.313, 383.701, 99.873]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 96.006, 100]} />
              <mesh geometry={(nodes.Sphere001_Nave_0 as Mesh).geometry} material={materials.Nave} position={[-677.886, -12.304, 94.554]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <mesh geometry={(nodes.Sphere002_Nave_0 as Mesh).geometry} material={materials.Nave} position={[-639.342, -12.304, 94.554]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[37.812, 28.604, 28.604]} />
              <mesh geometry={(nodes.Cylinder023_LuzRoja_0 as Mesh).geometry} material={materials.LuzRoja} position={[-1236.673, 411.161, 96.905]} rotation={[-1.531, -0.235, 0.011]} scale={[200, 141.882, 200.345]} />
              <mesh geometry={(nodes.Cylinder024_Nave_0 as Mesh).geometry} material={materials.Nave} position={[-1187.391, 406.067, 96.741]} rotation={[-1.577, -0.214, -0.007]} scale={[200, 135.497, 200.345]} />
              <mesh geometry={(nodes.Elbow_Joint002_Nave_0 as Mesh).geometry} material={materials.Nave} position={[-75.36, -76.389, 341.981]} rotation={[0, -0.155, 0]} scale={25.735} />
              <mesh geometry={(nodes.Plane_Nave_0 as Mesh).geometry} material={materials.Nave} position={[-94.666, 85.143, 294.19]} rotation={[-0.008, -0.002, 0.003]} scale={100} />
              <mesh geometry={(nodes.Cylinder004_Nave_0 as Mesh).geometry} material={materials.Nave} position={[-353.353, 58.897, 235.802]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
              <mesh geometry={(nodes.Elbow_Joint_Nave_0 as Mesh).geometry} material={materials.Nave} position={[-236.243, 116.039, 253.597]} rotation={[-0.491, -0.245, 1.56]} scale={36.343} />
              <mesh geometry={(nodes.Elbow_Joint001__0 as Mesh).geometry} material={materials['Elbow_Joint.001__0']} position={[-226.555, 113.264, 0]} rotation={[0, 0, Math.PI / 2]} scale={36.343} />
              <mesh geometry={(nodes.Cylinder006_Nave_0 as Mesh).geometry} material={materials.Nave} position={[-540.651, -242.298, -110.649]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <mesh geometry={(nodes.Cylinder017_Nave_0 as Mesh).geometry} material={materials.Nave} position={[-540.651, -242.298, 311.434]} rotation={[0.783, -0.205, 0.079]} scale={[143.864, 200, 199.08]} />
              <mesh geometry={(nodes.Cylinder008_Nave_0 as Mesh).geometry} material={materials.Nave} position={[-540.651, -242.298, -110.649]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <mesh geometry={(nodes.Cylinder009_LuzRoja_0 as Mesh).geometry} material={materials.LuzRoja} position={[-540.651, -242.298, -110.649]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <mesh geometry={(nodes.Cylinder016_LuzRoja_0 as Mesh).geometry} material={materials.LuzRoja} position={[-540.651, -242.298, 311.434]} rotation={[0.783, -0.205, 0.079]} scale={[143.864, 200, 199.08]} />
              <mesh geometry={(nodes.Cylinder018_Nave_0 as Mesh).geometry} material={materials.Nave} position={[-540.651, -242.298, 311.434]} rotation={[0.783, -0.205, 0.079]} scale={[143.864, 200, 199.08]} />
            </group>
          </group>
      </group>

      {/* Engine propulsion effects */}
      {config.engines.map((engine, index) => (
        <EnginePropulsion
          key={index}
          position={engine.position}
          scale={engine.scale}
          coreColor={engine.color}
        />
      ))}
    </group>
  )
}

useGLTF.preload('/models/planet-express.glb')
