/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 model.glb -o RickNMorty.tsx -t 
Author: Micheal-Holloway (https://sketchfab.com/Micheal-Holloway)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ricks-ship-from-rick-and-morty-71dce3dd627146e9a1e4776a490e786b
Title: Rick's ship from Rick and Morty
*/

import { useGLTF } from '@react-three/drei'
import { SHIP_CONFIGS } from '../config/shipConfigs'
import { EnginePropulsion } from '../effects'
import type { Mesh } from 'three'
import type { GLTFResult } from '../types'

const config = SHIP_CONFIGS['rick-n-morty']

export function RickNMorty() {
  const { nodes, materials } = useGLTF('/models/rick-n-morty.glb') as GLTFResult
  return (
    <group dispose={null}>
      <group
        scale={config.transform.scale}
        rotation={config.transform.rotation}
        position={config.transform.positionOffset}
      >
          <group position={[30.587, 50.542, 70.812]} rotation={[-Math.PI / 2, 0, 0]} scale={[5.766, 10.36, 5.766]}>
            <mesh geometry={(nodes.Cube003_Material014_0 as Mesh).geometry} material={materials['Material.014']} />
            <mesh geometry={(nodes.Cube003_Material015_0 as Mesh).geometry} material={materials['Material.015']} />
            <mesh geometry={(nodes.Cube003_Material012_0 as Mesh).geometry} material={materials['Material.012']} />
            <mesh geometry={(nodes.Cube003_Lights_0 as Mesh).geometry} material={materials.Lights} />
          </group>
          <group position={[86.196, 47.707, -5.715]} rotation={[-Math.PI / 2, 0.56, 0]} scale={[6.099, 1.321, 5.797]}>
            <mesh geometry={(nodes.Cube001_Material007_0 as Mesh).geometry} material={materials['Material.007']} />
            <mesh geometry={(nodes.Cube001_Material008_0 as Mesh).geometry} material={materials['Material.008']} />
          </group>
          <group position={[37.368, 31.29, 53.703]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[16.18, 16.18, 10.092]}>
            <mesh geometry={(nodes.Cylinder001_Tires_0 as Mesh).geometry} material={materials.Tires} />
            <mesh geometry={(nodes.Cylinder001_Rims_0 as Mesh).geometry} material={materials.Rims} />
          </group>
          <group position={[0, 36.708, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={(nodes.Circle_Material005_0 as Mesh).geometry} material={materials['Material.005']} />
            <mesh geometry={(nodes.Circle_MetalWithScratches_0 as Mesh).geometry} material={materials.MetalWithScratches} />
            <mesh geometry={(nodes.Circle_Rim_0 as Mesh).geometry} material={materials.material} />
            <mesh geometry={(nodes.Circle_Material017_0 as Mesh).geometry} material={materials['Material.017']} />
          </group>
          <mesh geometry={(nodes.Sphere003_LightGlass_0 as Mesh).geometry} material={materials.LightGlass} position={[30.541, 51.799, 80.9]} scale={8.26} />
          <mesh geometry={(nodes.Sphere002_LightGlass_0 as Mesh).geometry} material={materials.LightGlass} position={[-30.713, 51.799, 80.9]} scale={8.26} />
          <mesh geometry={(nodes.Circle002_Glass_Rim_0 as Mesh).geometry} material={materials.Glass_Rim} position={[-0.238, 65.178, 5.172]} scale={61.83} />
          <mesh geometry={(nodes.Sphere001_LightGlass_0 as Mesh).geometry} material={materials.LightGlass} position={[-0.774, 65.167, 0.301]} rotation={[-Math.PI / 2, 0, 0]} scale={60.035} />
          <mesh geometry={(nodes.Cube004_Material_0 as Mesh).geometry} material={materials.Material} position={[-17.047, 73.521, 4.414]} rotation={[Math.PI / 2, 0, 0]} scale={[-8.601, 4.786, 8.601]} />
          <mesh geometry={(nodes.Cube_Material_0 as Mesh).geometry} material={materials.Material} position={[24.286, 73.521, 4.414]} rotation={[Math.PI / 2, 0, 0]} scale={[-8.601, 4.786, 8.601]} />
          <mesh geometry={(nodes.Plane__0 as Mesh).geometry} material={materials.Plane__0} position={[44.97, 56.657, 67.735]} rotation={[Math.PI / 2, 0, 0]} scale={[14.236, 2.345, 13.144]} />
          <mesh geometry={(nodes.Cylinder002_Material009_0 as Mesh).geometry} material={materials['Material.009']} position={[91.55, 64.691, 4.215]} rotation={[-Math.PI / 2, 1.426, 0]} scale={[4.586, 4.586, 14.222]} />
          <mesh geometry={(nodes.Cylinder_Trashcan_0 as Mesh).geometry} material={materials.Trashcan} position={[91.017, 62.271, 0.021]} rotation={[0, 0, -0.208]} scale={[15.681, 15.681, 21.709]} />
      </group>

      {/* Engine propulsion effects */}
      {config.engines.map((engine, index) => (
        <EnginePropulsion
          key={index}
          position={engine.position}
          scale={engine.scale}
          coreColor={engine.color}
        />
      ))}
    </group>
  )
}

useGLTF.preload('/models/rick-n-morty.glb')
