/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 model.glb -o Rocketship.tsx -t
Author: motaman (https://sketchfab.com/motaman)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spaceship-0a073d0ab9a64b408056e82f7628b188
Title: Spaceship
*/

import { useGLTF } from '@react-three/drei'
import { SHIP_CONFIGS } from '../config/shipConfigs'
import type { Mesh } from 'three'
import type { GLTFResult } from '../types'


const config = SHIP_CONFIGS.rocketship

export function Rocketship() {
  const { nodes, materials } = useGLTF('/models/rocketship.glb') as GLTFResult
  return (
    <group dispose={null}>
      <group
        scale={config.transform.scale}
        rotation={config.transform.rotation}
        position={config.transform.positionOffset}
      >
        <mesh geometry={(nodes.Object_2 as Mesh).geometry} material={materials.lambert3SG} />
        <mesh geometry={(nodes.Object_3 as Mesh).geometry} material={materials.lambert4SG} />
        <mesh geometry={(nodes.Object_4 as Mesh).geometry} material={materials.initialShadingGroup} />
        <mesh geometry={(nodes.Object_5 as Mesh).geometry} material={materials.lambert2SG} />
      </group>

      {/* TODO: Add propulsion effects here */}
    </group>
  )
}

useGLTF.preload('/models/rocketship.glb')
