/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 model.glb -o SayanCapsule.tsx -t 
Author: Noddity (https://sketchfab.com/Noddity)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vegeta-spaceship-1f8b0948a55c465b99f93fbcb0a21502
Title: Vegeta SpaceShip
*/

import { useGLTF } from '@react-three/drei'
import { SHIP_CONFIGS } from '../config/shipConfigs'
import { EnginePropulsion } from '../effects'
import type { Mesh } from 'three'
import type { GLTFResult } from '../types'

const config = SHIP_CONFIGS['sayan-capsule']

export function SayanCapsule() {
  const { nodes, materials } = useGLTF('/models/sayan-capsule.glb') as GLTFResult
  return (
    <group dispose={null}>
      <group
        scale={config.transform.scale}
        rotation={config.transform.rotation}
        position={config.transform.positionOffset}
      >
          <group rotation={[-Math.PI / 2, 0, 0]} scale={0.212}>
            <mesh geometry={(nodes.Cube_Spaceship_0 as Mesh).geometry} material={materials.Spaceship} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
          </group>
      </group>

      {/* Engine propulsion effects */}
      {config.engines.map((engine, index) => (
        <EnginePropulsion
          key={index}
          position={engine.position}
          scale={engine.scale}
          coreColor={engine.color}
        />
      ))}
    </group>
  )
}

useGLTF.preload('/models/sayan-capsule.glb')
