/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 model.glb -o TieFighter.tsx -t 
Author: Mickael Boitte (https://sketchfab.com/boittemike1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-tie-fighter-star-wars-model-5375de94c2484ab0b2a2bd75aa63c2b4
Title: 3D T.I.E Fighter - Star Wars model
*/

import { useGLTF } from '@react-three/drei'
import { SHIP_CONFIGS } from '../config/shipConfigs'
import { EnginePropulsion } from '../effects'
import type { Mesh } from 'three'
import type { GLTFResult } from '../types'

const config = SHIP_CONFIGS['tie-fighter']

export function TieFighter() {
  const { nodes, materials } = useGLTF('/models/tie-fighter.glb') as GLTFResult
  return (
    <group dispose={null}>
      <group
        scale={config.transform.scale}
        rotation={config.transform.rotation}
        position={config.transform.positionOffset}
      >
          <group position={[0.68, -0.141, 0.358]} rotation={[-1.794, -0.3, -0.17]} scale={0.736}>
            <mesh geometry={(nodes.Object_2 as Mesh).geometry} material={materials['Material.001']} />
            <mesh geometry={(nodes.Object_3 as Mesh).geometry} material={materials['Material.002']} />
            <mesh geometry={(nodes.Object_4 as Mesh).geometry} material={materials['Material.003']} />
          </group>
      </group>

      {/* Engine propulsion effects */}
      {config.engines.map((engine, index) => (
        <EnginePropulsion
          key={index}
          position={engine.position}
          scale={engine.scale}
          coreColor={engine.color}
        />
      ))}
    </group>
  )
}

useGLTF.preload('/models/tie-fighter.glb')
