/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 model.glb -o RickNMorty.tsx -t 
Author: Micheal-Holloway (https://sketchfab.com/Micheal-Holloway)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ricks-ship-from-rick-and-morty-71dce3dd627146e9a1e4776a490e786b
Title: Rick's ship from Rick and Morty
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Sphere003_LightGlass_0: THREE.Mesh
    Sphere002_LightGlass_0: THREE.Mesh
    Circle002_Glass_Rim_0: THREE.Mesh
    Sphere001_LightGlass_0: THREE.Mesh
    Cube004_Material_0: THREE.Mesh
    Cube_Material_0: THREE.Mesh
    Plane__0: THREE.Mesh
    Cube003_Material014_0: THREE.Mesh
    Cube003_Material015_0: THREE.Mesh
    Cube003_Material012_0: THREE.Mesh
    Cube003_Lights_0: THREE.Mesh
    Cube001_Material007_0: THREE.Mesh
    Cube001_Material008_0: THREE.Mesh
    Cylinder002_Material009_0: THREE.Mesh
    Cylinder_Trashcan_0: THREE.Mesh
    Cylinder001_Tires_0: THREE.Mesh
    Cylinder001_Rims_0: THREE.Mesh
    Circle_Material005_0: THREE.Mesh
    Circle_MetalWithScratches_0: THREE.Mesh
    Circle_Rim_0: THREE.Mesh
    Circle_Material017_0: THREE.Mesh
  }
  materials: {
    LightGlass: THREE.MeshPhysicalMaterial
    Glass_Rim: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    Plane__0: THREE.MeshStandardMaterial
    ['Material.014']: THREE.MeshStandardMaterial
    ['Material.015']: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
    Lights: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    Trashcan: THREE.MeshStandardMaterial
    Tires: THREE.MeshStandardMaterial
    Rims: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    MetalWithScratches: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    ['Material.017']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/rick-n-morty.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[30.587, 50.542, 70.812]} rotation={[-Math.PI / 2, 0, 0]} scale={[5.766, 10.36, 5.766]}>
        <mesh geometry={nodes.Cube003_Material014_0.geometry} material={materials['Material.014']} />
        <mesh geometry={nodes.Cube003_Material015_0.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Cube003_Material012_0.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cube003_Lights_0.geometry} material={materials.Lights} />
      </group>
      <group position={[86.196, 47.707, -5.715]} rotation={[-Math.PI / 2, 0.56, 0]} scale={[6.099, 1.321, 5.797]}>
        <mesh geometry={nodes.Cube001_Material007_0.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube001_Material008_0.geometry} material={materials['Material.008']} />
      </group>
      <group position={[37.368, 31.29, 53.703]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[16.18, 16.18, 10.092]}>
        <mesh geometry={nodes.Cylinder001_Tires_0.geometry} material={materials.Tires} />
        <mesh geometry={nodes.Cylinder001_Rims_0.geometry} material={materials.Rims} />
      </group>
      <group position={[0, 36.708, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Circle_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Circle_MetalWithScratches_0.geometry} material={materials.MetalWithScratches} />
        <mesh geometry={nodes.Circle_Rim_0.geometry} material={materials.material} />
        <mesh geometry={nodes.Circle_Material017_0.geometry} material={materials['Material.017']} />
      </group>
      <mesh geometry={nodes.Sphere003_LightGlass_0.geometry} material={materials.LightGlass} position={[30.541, 51.799, 80.9]} scale={8.26} />
      <mesh geometry={nodes.Sphere002_LightGlass_0.geometry} material={materials.LightGlass} position={[-30.713, 51.799, 80.9]} scale={8.26} />
      <mesh geometry={nodes.Circle002_Glass_Rim_0.geometry} material={materials.Glass_Rim} position={[-0.238, 65.178, 5.172]} scale={61.83} />
      <mesh geometry={nodes.Sphere001_LightGlass_0.geometry} material={materials.LightGlass} position={[-0.774, 65.167, 0.301]} rotation={[-Math.PI / 2, 0, 0]} scale={60.035} />
      <mesh geometry={nodes.Cube004_Material_0.geometry} material={materials.Material} position={[-17.047, 73.521, 4.414]} rotation={[Math.PI / 2, 0, 0]} scale={[-8.601, 4.786, 8.601]} />
      <mesh geometry={nodes.Cube_Material_0.geometry} material={materials.Material} position={[24.286, 73.521, 4.414]} rotation={[Math.PI / 2, 0, 0]} scale={[-8.601, 4.786, 8.601]} />
      <mesh geometry={nodes.Plane__0.geometry} material={materials.Plane__0} position={[44.97, 56.657, 67.735]} rotation={[Math.PI / 2, 0, 0]} scale={[14.236, 2.345, 13.144]} />
      <mesh geometry={nodes.Cylinder002_Material009_0.geometry} material={materials['Material.009']} position={[91.55, 64.691, 4.215]} rotation={[-Math.PI / 2, 1.426, 0]} scale={[4.586, 4.586, 14.222]} />
      <mesh geometry={nodes.Cylinder_Trashcan_0.geometry} material={materials.Trashcan} position={[91.017, 62.271, 0.021]} rotation={[0, 0, -0.208]} scale={[15.681, 15.681, 21.709]} />
    </group>
  )
}

useGLTF.preload('/models/rick-n-morty.glb')
