/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 model.glb -o SpaceShuttle.tsx -t 
Author: ASHISH (https://sketchfab.com/3dmodelsmith)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/space-shuttle-892969a88e71495d9e869f96c95f0abf
Title: Space Shuttle
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube001_rocket_0: THREE.Mesh
    Cube002_rocket_0: THREE.Mesh
    Cube003_rocket_0: THREE.Mesh
    Cube004_rocket_0: THREE.Mesh
    Cube007_thruster_0: THREE.Mesh
    Cube005_thruster_0: THREE.Mesh
    Cube006_thruster_0: THREE.Mesh
    Cube008_thruster_0: THREE.Mesh
  }
  materials: {
    rocket: THREE.MeshStandardMaterial
    thruster: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/space-shuttle.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube001_rocket_0.geometry} material={materials.rocket} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube002_rocket_0.geometry} material={materials.rocket} rotation={[-Math.PI / 2, 0, 0]} scale={6.105} />
      <mesh geometry={nodes.Cube003_rocket_0.geometry} material={materials.rocket} rotation={[-Math.PI / 2, 0, 0]} scale={6.105} />
      <mesh geometry={nodes.Cube004_rocket_0.geometry} material={materials.rocket} rotation={[-Math.PI / 2, 0, 0]} scale={6.105} />
      <mesh geometry={nodes.Cube007_thruster_0.geometry} material={materials.thruster} position={[34.638, 2.49, -0.136]} rotation={[-Math.PI / 2, 0, 0]} scale={0.718} />
      <mesh geometry={nodes.Cube005_thruster_0.geometry} material={materials.thruster} position={[35.914, -3.114, 2.879]} rotation={[-Math.PI / 2, 0, 0]} scale={0.847} />
      <mesh geometry={nodes.Cube006_thruster_0.geometry} material={materials.thruster} position={[34.525, 2.49, -0.136]} rotation={[-Math.PI / 2, 0, 0]} scale={0.744} />
      <mesh geometry={nodes.Cube008_thruster_0.geometry} material={materials.thruster} position={[35.699, -3.117, 2.895]} rotation={[-Math.PI / 2, 0, 0]} scale={0.847} />
    </group>
  )
}

useGLTF.preload('/models/space-shuttle.glb')
