/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 model.glb -o Starship.tsx -t 
Author: MartianDays (https://sketchfab.com/MartianDays)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spacex-starship-a8a0b69f776841a1a465cd9fb3762fd2
Title: SpaceX Starship
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Bow_Window001_Starship_0: THREE.Mesh
    Primary_Hull001_Starship_0: THREE.Mesh
    Cargo_Doors001_Starship_0: THREE.Mesh
    SeaLev_Raptors_LP001_Starship_0: THREE.Mesh
    Vacuum_Raptors_LP001_Starship_0: THREE.Mesh
    Cargo_DropBoxes001_Starship_0: THREE.Mesh
    Cabin_WindowInset001_Starship_0: THREE.Mesh
    Cabin_Windows001_Starship_0: THREE.Mesh
  }
  materials: {
    Starship: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/starship.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, -5293.177, -42.376]} rotation={[Math.PI / 2, 0, 0]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh geometry={nodes.Bow_Window001_Starship_0.geometry} material={materials.Starship} rotation={[0, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes.Primary_Hull001_Starship_0.geometry} material={materials.Starship} rotation={[0, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes.Cargo_Doors001_Starship_0.geometry} material={materials.Starship} rotation={[0, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes.SeaLev_Raptors_LP001_Starship_0.geometry} material={materials.Starship} position={[0, 0, 123.114]} rotation={[0, 0, Math.PI / 2]} scale={[65.532, 65.532, 81.725]} />
          <mesh geometry={nodes.Vacuum_Raptors_LP001_Starship_0.geometry} material={materials.Starship} rotation={[0, 0, -Math.PI / 2]} scale={[65.532, 65.532, 81.725]} />
          <mesh geometry={nodes.Cargo_DropBoxes001_Starship_0.geometry} material={materials.Starship} position={[-1.126, -0.26, 0]} rotation={[0, 0, -Math.PI / 6]} scale={100} />
          <mesh geometry={nodes.Cabin_WindowInset001_Starship_0.geometry} material={materials.Starship} rotation={[0, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes.Cabin_Windows001_Starship_0.geometry} material={materials.Starship} rotation={[0, 0, Math.PI / 2]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/starship.glb')
